author: Zev Benjamin <zev@cpan.com>
build_requires: 
  Test::Builder::Tester: 0.64
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
name: Test-Dependencies
no_index: 
  directory: 
    - t-data
    - inc
    - t
requires: 
  B::PerlReq: 0
  File::Find::Rule: 0
  Module::CoreList: 0
  PerlReq::Utils: 0
  Test::Builder::Module: 0
  YAML: 0
version: 0.06
