author: Zev Benjamin <zev@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.59
license: perl
name: Test-Dependencies
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::CoreList: 0
  Pod::Strip: 0
version: 0.02
